### ISSUE TITLE
Publish to Flathub

### ISSUE THREAD

**Issue by robertaustinbell** [muelli/josm.openstreetmap.de#1]
Will this be published to Flathub?

**Comment by muelli** [comment]
It could be. But this flatpak is missing everything for desktop integration. That is an icon, a .desktop file, and appstream data.  Do you know where to find these?

Bonus points if we can build from source rather than taking the binary release.

**Comment by robertaustinbell** [comment]
So I'm just a user, please forgive me if I make any dumb comments. 
It looks like Appstream data come in the form of a .YAML and .XML file per this page  https://www.freedesktop.org/wiki/Distributions/AppStream/
So I think that can be found here
https://sources.debian.org/src/josm/0.0.svn14289+dfsg-1/build.xml/
Here is the one related to Snap
https://sources.debian.org/src/josm/0.0.svn14289+dfsg-1/snapcraft.yaml/
And I think this is the .desktop that your looking for 
https://josm.openstreetmap.de/browser/josm/trunk/linux/tested/usr/share/applications/josm.desktop
Fedora has a nice content display showing where everything is
https://apps.fedoraproject.org/packages/josm/contents/

**Comment by muelli** [comment]
cool. thanks. I've created https://github.com/flathub/flathub/pull/697/

Do you know how to build it from source?

**Comment by robertaustinbell** [comment]
I don't but I just sent a PM to someone who might.

**Comment by muelli** [comment]
are you interested in making a proper appstream file? cf. https://github.com/flathub/flathub/pull/697#issuecomment-434481241 and https://josm.openstreetmap.de/ticket/16923#ticket

**Comment by robertaustinbell** [comment]
I don't know how to do that but I would be willing to give it a shot.

**Comment by robertaustinbell** [comment]
I see the activity on the Flathub tracker. Thanks for all the work to put this together!   @muelli

**Comment by muelli** [comment]
we have the flatpak now on flathub. Let me close this and delete this repository entirely.
